### ISSUE TITLE
To install the spaCy model you need to run:

### ISSUE THREAD

**Issue by teebu** [cytora/pycon-nlp-in-10-lines#23]
This line doesn't work for me. 

```
To install the spaCy model you need to run:

sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0
```

Error:
```
sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\sputnik.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\sputnik\__main__.py", line 12, in main
    args.run(args)
  File "c:\python35\lib\site-packages\sputnik\cli.py", line 45, in run
    repository_url=args.repository_url)
  File "c:\python35\lib\site-packages\sputnik\__init__.py", line 30, in install
    pool = Pool(app_name, app_version, data_path)
  File "c:\python35\lib\site-packages\sputnik\pool.py", line 19, in __init__
    super(Pool, self).__init__(app_name, app_version, path, **kwargs)
  File "c:\python35\lib\site-packages\sputnik\package_list.py", line 33, in __init__
    self.load()
  File "c:\python35\lib\site-packages\sputnik\package_list.py", line 51, in load
    for package in self.packages():
  File "c:\python35\lib\site-packages\sputnik\package_list.py", line 47, in packages
    yield self.__class__.package_class(path=os.path.join(self.path, path))
  File "c:\python35\lib\site-packages\sputnik\package.py", line 15, in __init__
    super(Package, self).__init__(defaults=meta['package'])
KeyError: 'package'
```

I guess the equivalent is: 
```python -m spacy download en```

**Comment by keithbriggs** [comment]
Doesn't work for me either:

kbriggs:~/pycon-nlp-in-10-lines> sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0
Couldn't find or load handler for command 'spacy'
